#Logging
logging.config: classpath:logback-default.xml

spring:
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      # Check class tools.jackson.databind.cfg.ConfigFeature.SerializationFeature
      FAIL_ON_EMPTY_BEANS: false
    generator:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_KEYS_AS_TIMESTAMPS: true
      WRITE_DURATIONS_AS_TIMESTAMPS: true
      WRITE_ENUMS_USING_TO_STRING: false
  jackson-custom:
    serialization:
      local-date-format: yyyy-MM-dd
      local-time-format: hh:mm:ss
      zoned-date-time-format: yyyy-MM-dd'T'HH:mm:ss'Z'
tech:
  corefinance:
    app:
      converter:
        local-date-to-string: true
        local-date-time-to-string: true
        zoned-date-time-to-string: true
        zoned-date-time-to-local-date-time: true
        zoned-date-time-to-date: true
    common:
      filter-ordered:
        authen-filter: 2
        tenant-id-filter-order: 3
        trace-info-id-order: 1
        encoding-response-order: 0
      enabled:
        async: true
        simple-version: true
        auto-response-encoding: true
        trace-id-filter: true
        tenant: true
      default-response-charset: utf-8
      generic-exception-handling: true
    log:
      enabled:
        services: true
        repositories: true
        api: true
    security:
      internal-api-key: No-key
      # Json Web Token
      jwt:
        expiration: 3600
        login-mode: SINGLE_LOGIN_PER_APP
        enabled:
          common: true
      public-key: classpath:public_key.der
      private-key: classpath:private_key.der
      no-authen-urls:
        - /
        - /void
        - /parserConfigurationException
        - /throwable
        - /test/api/*
      permission:
        default-control: ALLOWED
      authorize-check: true
      scan-controllers-actions: true
      ignore-controller-scan:
        - .springframework.
        - .springdoc.
        - .test.
      url-cors:
        cors-configurations:
          - url-pattern: /v3/api-docs/*
            allowed-origins:
              - http://localhost:4200
            allowed-methods:
              - GET
            allowed-headers: '*'
          - url-pattern: /**
            allowed-origins:
              - http://localhost:4200
              - http://*.corefinance.tech
            allowed-methods:
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - POST
              - PATCH
            allowed-headers: '*'
    audit:
      enabled:
        zoned-date-time: true
        basic-user: true
        delete-track: true
export:
  format:
    date: yyyy/MM/dd
    datetime: yyyy/MM/dd HH:mm:ss
jasypt:
  encryptor:
    password: password
    # algorithm: PBEWithHmacSHA512AndAES_256
    algorithm: PBEWithMD5AndDES
    salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
    # provider-class-name: com.sun.crypto.provider.SunJCE
    provider-name: SunJCE
    string-output-type: base64
    key-obtention-iterations: 1000
    pool-size: 1