#Logging
logging.config: classpath:logback-default.xml

spring:
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      # Check class tools.jackson.databind.cfg.ConfigFeature.SerializationFeature
      FAIL_ON_EMPTY_BEANS: false
    generator:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_KEYS_AS_TIMESTAMPS: true
      WRITE_DURATIONS_AS_TIMESTAMPS: true
      WRITE_ENUMS_USING_TO_STRING: false
  data:
    mongodb:
      database: core_finance

tech:
  corefinance:
    common-mongodb:
      converter:
        zoned-date-time: true
        zonedDateTime: true
    audit:
      enabled:
        zoned-date-time: true
        basic-user: true
    initial:
      name-separator: _
      version-separator: .
      data-regex:
        permission:
          file-name-regex: classpath:initial/*permissions*.json
          replace-if-existed: true
        internal-api:
          file-name-regex: classpath:initial/*internal_api*.json
          replace-if-existed: true